//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class SettingsBlockLib : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBlockLib defaultInstance = ((SettingsBlockLib)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBlockLib())));
        
        public static SettingsBlockLib Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastfourpath {
            get {
                return ((string)(this["lastfourpath"]));
            }
            set {
                this["lastfourpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MaxiEnters {
            get {
                return ((int)(this["MaxiEnters"]));
            }
            set {
                this["MaxiEnters"] = value;
            }
        }
    }
}
